---
- hosts: all
  gather_facts: yes
  collections:
    - ibm.power_aix
  tasks:
    - name: Creation of a JFS2 filesystem
      filesystem:
        state: present
        filesystem: /mnt3
        fs_type: jfs2
        attributes: size=32768,isnapshot='no'
        mount_group: test
        vg: rootvg
